routes/web.php
<?php
$backEndPrefix = 'Backend\\';
$frontEndPrefix = 'Frontend\\';

Route::get('/', ['uses' => $frontEndPrefix.'HomeController@index', 'as' => 'home']);
Route::get('/createnotifications', ['uses' => $frontEndPrefix.'NotificationsController@createnotifications', 'as' => 'createnotifications']);
Route::any('login', ['uses' => $frontEndPrefix.'LoginController@index', 'as' => 'login']);
Route::get('logout', ['uses' => $frontEndPrefix.'LoginController@logout', 'as' => 'logout']);
Route::any('forgot', ['uses' => $frontEndPrefix.'LoginController@forgot', 'as' => 'forgot']);
Route::any('registration', ['uses' => $frontEndPrefix.'RegistrationController@index', 'as' => 'registration']);
Route::get('sitemap', ['uses' => $frontEndPrefix.'SitemapController@index', 'as' => 'sitemap']);
Route::get('sitemapxml', ['uses' => $frontEndPrefix.'SitemapController@sitemapxml', 'as' => 'sitemapxml']);
Route::get('article/{slug}', ['uses' => $frontEndPrefix.'ArticleController@index', 'as' => 'article']);
Route::get('catalog', ['uses' => $frontEndPrefix.'CatalogController@index', 'as' => 'catalog']);
Route::get('catalog/{slug}', ['uses' => $frontEndPrefix.'CatalogController@industry', 'as' => 'catalog.industry']);
Route::get('catalog/{slug1}/{slug2}', ['uses' => $frontEndPrefix.'CatalogController@type', 'as' => 'catalog.industry.type']);
Route::post('api/gettoken', ['uses' => $frontEndPrefix.'ApiController@gettoken']);
Route::post('api/{method}', ['uses' => $frontEndPrefix.'ApiController@method']);

Route::group(['middleware' => 'auth'], function() use ($frontEndPrefix) {
    
    Route::get('account', ['uses' => $frontEndPrefix.'AccountController@index', 'as' => 'account']);
    Route::post('account/dashboard_setup', ['uses' => $frontEndPrefix.'AccountController@setup', 'as' => 'dashboard_setup']);
    Route::group(['middleware' => 'accountrolecheck'], function() use ($frontEndPrefix) {
        //account settings
        Route::any('account/settings', ['uses' => $frontEndPrefix.'AccountController@settings', 'as' => 'settings']);
        //account prices  
        Route::get('account/prices', ['uses' => $frontEndPrefix.'PricesController@index', 'as' => 'prices']);
        Route::any('account/prices/create', ['uses' => $frontEndPrefix.'PricesController@create', 'as' => 'prices.create']);
        Route::any('account/prices/edit/{id}', ['uses' => $frontEndPrefix.'PricesController@edit', 'as' => 'prices.edit']);
        Route::any('account/prices/editcustom/{id}', ['uses' => $frontEndPrefix.'PricesController@editcustom', 'as' => 'prices.editcustom']);
        Route::any('account/prices/delete/{id}', ['uses' => $frontEndPrefix.'PricesController@delete', 'as' => 'prices.delete']);  
        //account branches
        Route::get('account/branches', ['uses' => $frontEndPrefix.'BranchesController@index', 'as' => 'branches']);
        Route::any('account/branches/create', ['uses' => $frontEndPrefix.'BranchesController@create', 'as' => 'branches.create']);
        Route::any('account/branches/store', ['uses' => $frontEndPrefix.'BranchesController@store', 'as' => 'branches.store']);
        Route::any('account/branches/edit/{id}', ['uses' => $frontEndPrefix.'BranchesController@edit', 'as' => 'branches.edit']);
        Route::any('account/branches/update/{id}', ['uses' => $frontEndPrefix.'BranchesController@update', 'as' => 'branches.update']);
        Route::any('account/branches/delete/{id}', ['uses' => $frontEndPrefix.'BranchesController@delete', 'as' => 'branches.delete']);
        //account staff
        Route::get('account/staff', ['uses' => $frontEndPrefix.'StaffController@index', 'as' => 'staff']);
        Route::any('account/staff/create', ['uses' => $frontEndPrefix.'StaffController@create', 'as' => 'staff.create']);
        Route::any('account/staff/edit/{id}', ['uses' => $frontEndPrefix.'StaffController@edit', 'as' => 'staff.edit']);
        Route::any('account/staff/delete/{id}', ['uses' => $frontEndPrefix.'StaffController@delete', 'as' => 'staff.delete']);
        //account portfolio
        Route::get('account/portfolios', ['uses' => $frontEndPrefix.'PortfoliosController@index', 'as' => 'portfolios']);
         Route::any('account/portfolios/create', ['uses' => $frontEndPrefix.'PortfoliosController@create', 'as' => 'portfolio.create']);
        Route::any('account/portfolios/edit/{id}', ['uses' => $frontEndPrefix.'PortfoliosController@edit', 'as' => 'portfolio.edit']);
        Route::any('account/portfolios/delete/{id}', ['uses' => $frontEndPrefix.'PortfoliosController@delete', 'as' => 'portfolio.delete']);
        //account reviews
        Route::get('account/reviews', ['uses' => $frontEndPrefix.'ReviewsController@index', 'as' => 'reviews']);
        Route::get('account/reviews/edit/{id}', ['uses' => $frontEndPrefix.'ReviewsController@edit', 'as' => 'reviews.edit']);
        //account orders
        Route::get('account/orders', ['uses' => $frontEndPrefix.'OrdersController@index', 'as' => 'orders']);
        Route::get('account/orders/edit/{id}', ['uses' => $frontEndPrefix.'OrdersController@edit', 'as' => 'orders.edit']);
        Route::post('account/orders/update/{id}', ['uses' => $frontEndPrefix.'OrdersController@update', 'as' => 'orders.update']);
        //account invoices
        Route::get('account/invoices', ['uses' => $frontEndPrefix.'InvoicesController@index', 'as' => 'invoices']);
        Route::get('account/invoices/edit/{id}', ['uses' => $frontEndPrefix.'InvoicesController@edit', 'as' => 'invoices.edit']);
        Route::post('account/invoices/update/{id}', ['uses' => $frontEndPrefix.'InvoicesController@update', 'as' => 'invoices.update']);
        //account reports
        Route::get('account/reports', ['uses' => $frontEndPrefix.'ReportsController@index', 'as' => 'reports']);
        Route::post('account/reports/excel', ['uses' => $frontEndPrefix.'ReportsController@excel', 'as' => 'excel']);
        Route::get('account/reports/{slug}', ['uses' => $frontEndPrefix.'ReportsController@report', 'as' => 'report']);
        //account labs
        Route::get('account/mylabs', ['uses' => $frontEndPrefix.'LabsController@index', 'as' => 'mylabs']);
        //account tickets
        Route::any('account/tickets', ['uses' => $frontEndPrefix.'TicketsController@index', 'as' => 'tickets']);
        //account notifications
        Route::any('account/notifications', ['uses' => $frontEndPrefix.'NotificationsController@index', 'as' => 'notifications']);
    });

    Route::group(['middleware' => 'guestcheck'], function() use ($frontEndPrefix) {
        Route::get('checkout', ['uses' => $frontEndPrefix.'CheckoutController@index', 'as' => 'checkout']);
        Route::post('checkout/create', ['uses' => $frontEndPrefix.'CheckoutController@create', 'as' => 'checkout.create']);
    });
});

Route::group(['middleware' => 'postcheck'], function() use ($frontEndPrefix) {
    Route::any('/ajax/getData', ['uses' => $frontEndPrefix.'AjaxController@getData']);    
});

Route::group(['prefix' => 'admin', 'as' => 'voyager.'], function ()  use ($backEndPrefix) {
    Route::get('login', ['uses' => $backEndPrefix.'VoyagerAuthController@login',     'as' => 'login']);
    Route::post('login', ['uses' => $backEndPrefix.'VoyagerAuthController@postLogin', 'as' => 'postlogin']);

    Route::group(['middleware' => 'admin.user'], function () use ($backEndPrefix) {
        Route::get('/', ['uses' => $backEndPrefix.'VoyagerController@index',   'as' => 'dashboard']);
        Route::post('logout', ['uses' => $backEndPrefix.'VoyagerController@logout',  'as' => 'logout']);
        Route::post('upload', ['uses' => $backEndPrefix.'VoyagerController@upload',  'as' => 'upload']);

        Route::post('industry-services/getservices', ['uses' => $backEndPrefix.'VoyagerIndustryServiceController@getservices',  'as' => 'getservices']);
        Route::post('industry-services/getoptions', ['uses' => $backEndPrefix.'VoyagerIndustryServiceController@getoptions',  'as' => 'getoptions']);
        Route::post('branches/getbranches', ['uses' => $backEndPrefix.'VoyagerBranchController@getbranches',  'as' => 'getbranches']);

        Route::get('profile', ['uses' => $backEndPrefix.'VoyagerUserController@profile', 'as' => 'profile']);

        try {
            foreach (Voyager::model('DataType')::all() as $dataType) {
                $breadController = $dataType->controller
                                 ? Str::start($dataType->controller, '\\')
                                 : $backEndPrefix.'VoyagerBaseController';

                Route::get($dataType->slug.'/order', $breadController.'@order')->name($dataType->slug.'.order');
                Route::post($dataType->slug.'/action', $breadController.'@action')->name($dataType->slug.'.action');
                Route::post($dataType->slug.'/order', $breadController.'@update_order')->name($dataType->slug.'.order');
                Route::get($dataType->slug.'/{id}/restore', $breadController.'@restore')->name($dataType->slug.'.restore');
                Route::get($dataType->slug.'/relation', $breadController.'@relation')->name($dataType->slug.'.relation');
                Route::post($dataType->slug.'/remove', $breadController.'@remove_media')->name($dataType->slug.'.media.remove');
                Route::resource($dataType->slug, $breadController, ['parameters' => [$dataType->slug => 'id']]);
            }
        } catch (\InvalidArgumentException $e) {
            throw new \InvalidArgumentException("Custom routes hasn't been configured because: ".$e->getMessage(), 1);
        } catch (\Exception $e) {
            
        }

        Route::resource('roles', $backEndPrefix.'VoyagerRoleController');

        Route::group([
            'as'     => 'menus.',
            'prefix' => 'menus/{menu}',
        ], function () use ($backEndPrefix) {
            Route::get('builder', ['uses' => $backEndPrefix.'VoyagerMenuController@builder',    'as' => 'builder']);

app/Http/Controllers/Backend/VoyagerAuthController.php
<?php
namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Http\Controllers\VoyagerAuthController as BaseVoyagerAuthController;

class VoyagerAuthController extends BaseVoyagerAuthController
{
    use AuthenticatesUsers;

    public function login()
    {
        if ($this->guard()->user()) {
            return redirect()->route('voyager.dashboard');
        }

        return Voyager::view('voyager::login');
    }

    public function postLogin(Request $request)
    {
        $this->validateLogin($request);

        // If the class is using the ThrottlesLogins trait, we can automatically throttle
        // the login attempts for this application. We'll key this by the username and
        // the IP address of the client making these requests into this application.
        if ($this->hasTooManyLoginAttempts($request)) {
            $this->fireLockoutEvent($request);

            return $this->sendLockoutResponse($request);
        }

        $credentials = $this->credentials($request);

        if ($this->guard()->attempt($credentials, $request->has('remember'))) {
            return $this->sendLoginResponse($request);
        }

        // If the login attempt was unsuccessful we will increment the number of attempts
        // to login and redirect the user back to the login form. Of course, when this
        // user surpasses their maximum number of attempts they will get locked out.
        $this->incrementLoginAttempts($request);

        return $this->sendFailedLoginResponse($request);
    }

    /*
     * Preempts $redirectTo member variable (from RedirectsUsers trait)
     */
    public function redirectTo()
    {
        return config('voyager.user.redirect', route('voyager.dashboard'));
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard(app('VoyagerGuard'));
    }
}

app/Http/Controllers/Backend/VoyagerBannerController.php
<?php

namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use TCG\Voyager\Facades\Voyager;
use App\Models\Banner;

class VoyagerBannerController extends Controller
{
    private $model;
    private $type;   

    public function __construct() {        
        $this->model = app('App\Models\Banner');
        $this->type = 'banners'; 
    }

    public function index(Request $request) {       
        $this->authorize('browse', $this->model);

        $type = $this->type;
        $model = $this->model;       
        $requests = $request->getQueryString();       

        $filter = [
            'filter_status' => $request->get('status'),
            'filter_search' => $request->get('search'),
        ];

        $many = Banner::orderBy('id', 'DESC');

        if ($filter['filter_status']) $many->where('status', $filter['filter_status']);       
        if ($filter['filter_search']) $many->where('name', 'LIKE', $filter['filter_search'].'%');

        $many = $many->paginate(20);

        return view('Backend.'.$type.'.browse', compact(
            'many',
            'type',
            'model',
            'filter',
            'requests'
        ));

    }    

    public function create(Request $request) { 
    //not used for this project    	
        $this->authorize('add', $this->model);        
    }

    public function store(Request $request) { 
    //not used for this project   	
        $this->authorize('add', $this->model);        
    }

    public function show(Request $request, $id)
    {
        //not used for this project
    }

    public function edit(Request $request, $id)
    {
        $this->authorize('edit', $this->model); 

        $data = Banner::where('id', (int)$id)->first();        
        $type = $this->type;
        $model = $this->model; 

        $requests = $request->getQueryString();       

        return view('Backend.'.$type.'.edit-add', compact(
            'data',
            'model',
            'type',
            'requests'
        ));
    }
   
    public function update(Request $request, $id)
    {
        $this->authorize('edit', $this->model);

        $data = Banner::where('id', (int)$id)->first();

        $messages = array(
            'name.required' => 'Name field is required!',                
            'name.max' => 'Name field contains more then 255 symbols!',            
        );

        $rules = array(
            'name' => 'required|max:255'
        );

        $request->validate($rules, $messages);            

        if (!$request->ajax()) { 
            $data->name = $request->input('name');
            $data->link = $request->input('link') ? $request->input('link') : null;
            $data->position = $request->input('position');
            $data->sort_order = $request->input('sort_order') ? (int)$request->input('sort_order') : 0;
            $data->status = $request->input('status');

            if ($request->file('image')) {
                $image_name = time().'.'.$request->file('image')->getClientOriginalExtension();                        
                $image = 'banners/'.$image_name;
                
                $request->file('image')->move(public_path().'/storage/banners/', $image_name); 

                $data->image = $image;
            }
                        
            $data->save();
        }

        return redirect()
            ->route('voyager.'.$this->type.'.index', $request->getQueryString())
            ->with([
                'message'    => __('voyager.generic.successfully_updated'),
                'alert-type' => 'success',
            ]);
    }

    public function destroy(Request $request, $id) {       
        $this->authorize('delete', $this->model);

        if (empty($id)) {           
            $ids = explode(',', $request->ids);
        } else {           
            $ids = array($id);
        }

        foreach ($ids as $id) {
            Banner::where('id', $id)->delete();            
        }

        return redirect()
            ->route('voyager.'.$this->type.'.index', $request->getQueryString())
            ->with([
                'message'    => __('voyager.generic.successfully_deleted'),
                'alert-type' => 'success'
            ]);
    }
}

app/Http/Controllers/Backend/VoyagerBaseController.php
<?php

namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\VoyagerBaseController as BaseVoyagerBaseController;

class VoyagerBaseController extends BaseVoyagerBaseController
{

}

app/Http/Controllers/Backend/VoyagerBreadController.php
<?php
namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\VoyagerBreadController as BaseVoyagerBreadController;

class VoyagerBreadController extends BaseVoyagerBreadController
{
   
}

app/Http/Controllers/Backend/VoyagerCompassController.php
<?php

namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\VoyagerCompassController as BaseVoyagerCompassController;

class VoyagerCompassController extends BaseVoyagerCompassController
{
    
}

app/Http/Controllers/Backend/VoyagerDatabaseController.php
<?php

namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\VoyagerDatabaseController as BaseVoyagerDatabaseController;

class VoyagerDatabaseController extends BaseVoyagerDatabaseController
{
    
}

app/Http/Controllers/Backend/VoyagerMediaController.php
<?php

namespace App\Http\Controllers\Backend;

use TCG\Voyager\Http\Controllers\VoyagerMediaController as BaseVoyagerMediaController;

class VoyagerMediaController extends BaseVoyagerMediaController
{
    
}

resources/views/Backend/branches/edit-add.blade.php
@extends('voyager::master')

@section('page_title', __('voyager::generic.'.(isset($data->id) ? 'edit' : 'add')).' '.$data->name)

@section('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('page_header')
    <h1 class="page-title">
        <i class="voyager-edit"></i>
        {{ __('voyager::generic.'.(isset($data->id) ? 'edit' : 'add')).' '.$data->name }}
    </h1>
@stop

@section('content')
    <div class="page-content container-fluid">
        <form class="form-edit-add" role="form" action="@if(!is_null($data->id)){{ route('voyager.'.$type.'.update', [$data->id, $requests]) }}@else{{ route('voyager.'.$type.'.store', [$requests]) }}@endif" method="POST" enctype="multipart/form-data" autocomplete="off">            
            @if(isset($data->id))
                {{ method_field("PUT") }}
            @endif
            {{ csrf_field() }}

            <div class="row">
                <div class="col-md-12">
                    <div class="panel panel-bordered">  
                        <div class="panel-body">                 
                            @if (count($errors) > 0)
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif                                                    
                            <div class="form-group">
                                <label for="status">{{ __('adm.status') }}</label>
                                <select class="form-control" name="status">        
                                    <option value="1" @if(isset($data->status) && $data->status == 1) selected @endif>Active</option>       
                                    <option value="2" @if(isset($data->status) && $data->status == 2) selected @endif>Suspended</option>
                                    <option value="3" @if(isset($data->status) && $data->status == 3) selected @endif>Blocked</option>
                                    <option value="4" @if(isset($data->status) && $data->status == 4) selected @endif>Removed</option>     
                                </select>
                            </div> 
                            <div class="form-group">
                                <label for="verified">Verified status</label>                                
                                <select class="form-control" name="verified">
                                    <option value="1" @if(isset($data->verified) && $data->verified == 1) selected @endif>Verified</option>       
                                    <option value="2" @if(isset($data->verified) && $data->verified == 2) selected @endif>Not verified</option>
                                </select>                                
                            </div>
                            
                            <div class="form-group">
                                <label for="name">{{ __('adm.name') }}</label>
                                <input type="text" class="form-control" id="name" name="name" placeholder="{{ __('adm.name') }}" value="{{ old('name', $data->name ?? '') }}">
                            </div> 
                            <div class="form-group">
                                <label for="description">{{ __('adm.description') }}</label>
                                <textarea class="form-control" id="description" name="description" placeholder="{{ __('adm.description') }}">{{ old('description', $data->description ?? '') }}</textarea>
                            </div>  
                            <div class="form-group">
                                <label for="email">{{ __('adm.email') }}</label>
                                <input type="email" class="form-control" id="email" name="email" placeholder="{{ __('adm.email') }}" value="{{ old('email', $data->email ?? '') }}">
                            </div>                          
                            <div class="form-group">
                                <label for="phone">{{ __('adm.phone') }}</label>
                                <input type="text" class="form-control" id="phone" name="phone" placeholder="{{ __('adm.phone') }}" value="{{ old('phone', $data->phone ?? '') }}">
                            </div>
                            @if(!is_null($data->id))
                                <div class="form-group">
                                    <label for="address">{{ __('adm.address') }}</label>
                                    <input type="text" class="form-control" id="address" value="{{ $address }}" disabled="disabled">
                                </div>  
                            @endif 
                            <div class="form-group">
                                <label for="charge_value">Custom service charge value (0,01 = 1% ... 0.99 = 99%)</label>
                                <input type="text" class="form-control" id="charge_value" name="charge_value" placeholder="Custom service charge value" value="{{ old('charge_value', $data->charge_value ?? '') }}">
                            </div>
                            <p>Manual coordinate detection service - <strong><a target="_blank" href="https://3planeta.com/gps-tools/ru/index.html">---Click---</a></strong></p>
                            <div class="form-group">
                                <label for="latitude">Latitude</label>
                                <input type="text" class="form-control" name="latitude" id="latitude" placeholder="Latitude" value="{{ old('latitude', $latitude ?? '') }}">
                            </div>
                            <div class="form-group">
                                <label for="longitude">Longitude</label>
                                <input type="text" class="form-control" name="longitude" id="longitude" placeholder="Longitude" value="{{ old('longitude', $longitude ?? '') }}">
                            </div>
                            @if(isset($data->logo) && $data->logo != '')
                            <div class="form-group">
                                <label for="logo">{{ __('adm.image') }}</label>
                                
                                    <img src="{{ filter_var($data->logo, FILTER_VALIDATE_URL) ? $data->logo : Voyager::image( $data->logo ) }}" style="width:200px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:10px;" />
                               
                            </div>
                            @endif
                            <input type="hidden" name="price" value="@if($price){{ $price->id }}@endif">
                        </div>
                    </div>
                </div>                
            </div>

            <button type="submit" class="btn btn-primary pull-right save">
                {{ __('voyager::generic.save') }}
            </button>
            <div class="clearfix"></div>
        </form>
        @if (count($staff))
        <br>
        <br>
        <div class="panel panel-bordered"> 
            <div class="panel-body">
                <h3>Department staff</h3>
                <br>                
                <ul>
                @foreach ($staff as $user)
                	@if ($user->user) 
                   	 <li><a href="{{ route('voyager.users.edit', [$user->user_id]) }}">{{ $user->user->name.' '.$user->user->surname.' ('.$user->role->display_name.')' }}</a></li>
                    @endif
                @endforeach
                </ul>
            </div> 
        </div>
        @endif
        @if (count($portfolio))
        <br>
        <br>
        <div class="panel panel-bordered"> 
            <div class="panel-body">
                <h3>Department portfolio</h3>
                <br>                
                @foreach ($portfolio as $image) 
                    <img src="{{ App\Services\Img::getThumb($image->image) }}" style="width:125px; height:auto; clear:both; display:block; padding:2px; border:1px solid #ddd; margin-bottom:20px;margin-right: 15px; display: inline-block; vertical-align:top" />
                @endforeach
                <br>

                <p><a class="btn btn-primary pull-right" href="{{ route('voyager.portfolios.index', ['search' => $data->name ]) }}">Manage location portfolio</a></p>
                <div class="clearfix"></div>
            </div> 
        </div>
        @endif

        <iframe id="form_target" name="form_target" style="display:none"></iframe>
        <form id="my_form" action="{{ route('voyager.upload') }}" target="form_target" method="post" enctype="multipart/form-data" style="width:0px;height:0;overflow:hidden">
            {{ csrf_field() }}
            <input name="image" id="upload_file" type="file" onchange="$('#my_form').submit();this.value='';">
            <input type="hidden" name="type_slug" id="type_slug" value="{{ $type }}">
        </form>
    </div>
@stop

@section('javascript')
    <script>
        $('document').ready(function () {
            $('.toggleswitch').bootstrapToggle();
        });
    </script>
@stop